import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../src/engine.js';
import {createLevel,FLOOR} from '../src/level.js';
function tick(g,seconds,input={}){for(let i=0;i<seconds*120;i++)g.step(1/120,input)}
function grounded(g,x=150){Object.assign(g.player,{x,y:FLOOR-g.player.h,vy:0,vx:0,grounded:true});return g.player}
test('player lands reliably and buffered jump leaves the ground',()=>{const g=new Game();g.mode='playing';tick(g,1);assert.equal(g.player.y+g.player.h,FLOOR);assert.ok(g.player.grounded);g.step(1/120,{jump:true,jumpPressed:true});assert.ok(g.player.vy<0);assert.ok(g.player.y+g.player.h<FLOOR)});
test('holding jump produces greater height than tapping; coyote jump works',()=>{const height=hold=>{const g=new Game();g.mode='playing';grounded(g);g.step(1/120,{jump:true,jumpPressed:true});let top=g.player.y;for(let i=0;i<80;i++){g.step(1/120,{jump:hold});top=Math.min(top,g.player.y)}return top};assert.ok(height(true)<height(false)-35);const g=new Game();g.mode='playing';grounded(g);g.step(1/120,{});g.player.grounded=false;g.step(1/120,{jump:true,jumpPressed:true});assert.ok(g.player.vy<-500)});
test('capsule transforms the same hero and damage downgrades before costing a life',()=>{const g=new Game();g.mode='playing';grounded(g);const foot=g.player.y+g.player.h;g.power();assert.equal(g.player.super,true);assert.equal(g.player.y+g.player.h,foot);assert.equal(g.player.h,78);tick(g,1);g.player.invuln=0;g.damage();assert.equal(g.player.super,false);assert.equal(g.lives,3);g.damage();assert.equal(g.lives,3);g.player.invuln=0;g.damage();assert.equal(g.lives,2);tick(g,1.2);assert.equal(g.level.cave,false);assert.ok(g.player.invuln>0)});
test('collision against a pipe blocks walking but jumping clears it',()=>{const g=new Game();g.mode='playing';grounded(g,1175);tick(g,.6,{right:true});assert.ok(g.player.x+g.player.w<=1250);g.step(1/120,{jump:true,jumpPressed:true,right:true});tick(g,1,{right:true,jump:true});assert.ok(g.player.x>1340)});
test('secret pipe enters cavern and exit restores the main route',()=>{const g=new Game();g.mode='playing';const pipe=g.main.pipes.find(p=>p.secret);Object.assign(g.player,{x:pipe.x+25,y:pipe.y-g.player.h,grounded:true});g.step(1/120,{down:true});assert.ok(g.transition);tick(g,.7);assert.ok(g.level.cave);const exit=g.cavern.pipes.find(p=>p.exit);g.travel(exit);tick(g,.7);assert.equal(g.level.cave,false);assert.ok(g.player.x>pipe.x)});
test('checkpoint, picked items, score, and lives survive save/continue',()=>{const g=new Game();g.mode='playing';grounded(g,9501);g.pickup(g.main.items[0]);g.step(1/120,{});assert.equal(g.checkpoint,9500);const h=new Game();h.reset(JSON.parse(JSON.stringify(g.snapshot())));assert.equal(h.player.x,9500);assert.ok(h.main.items[0].taken);assert.equal(h.coins,1);assert.equal(h.score,100)});
test('paws award completion bonus and 100 coins award a life',()=>{const g=new Game();g.mode='playing';for(const l of [g.main,g.cavern])for(const it of l.items.filter(i=>i.type==='paw'))g.pickup(it);assert.equal(g.paws,3);assert.equal(g.score,6000);g.coins=99;g.pickup(g.main.items.find(i=>i.type==='coin'));assert.equal(g.coins,100);assert.equal(g.lives,4)});
test('armored cats take two normal stomps, power punches defeat them',()=>{const g=new Game();g.mode='playing';const e=g.main.enemies.find(e=>e.type==='armor');for(let i=0;i<2;i++){Object.assign(g.player,{x:e.x+5,y:e.y-g.player.h-1,vy:250,vx:0});g.step(.02,{});if(i===0){assert.equal(e.hp,1);assert.ok(e.alive)}}assert.equal(e.alive,false);assert.equal(g.kills,1);const e2=g.main.enemies.find(e=>e.type==='armor'&&e.alive);g.power();g.transform=0;Object.assign(g.player,{x:e2.x-55,y:FLOOR-g.player.h,face:1,grounded:true});g.step(.02,{attackPressed:true});assert.equal(e2.alive,false)});
test('last life reaches game over and restarting resets the run',()=>{const g=new Game();g.mode='playing';g.lives=1;g.damage(true);tick(g,1.2);assert.equal(g.mode,'gameover');g.reset();assert.equal(g.mode,'playing');assert.equal(g.lives,3);assert.equal(g.coins,0)});
test('finish produces victory once with a stable bonus and paused physics stays still',()=>{const g=new Game();g.mode='playing';grounded(g,g.main.goal);g.step(.02,{});assert.equal(g.mode,'won');const score=g.score;tick(g,1);assert.equal(g.score,score);g.reset();g.mode='paused';const x=g.player.x;tick(g,1,{right:true});assert.equal(g.player.x,x);assert.equal(g.elapsed,0)});
test('all mandatory gaps are jumpable and each elevated reward has reachable support',()=>{const l=createLevel();const ground=l.platforms.filter(s=>s.type==='grass');for(let i=1;i<ground.length;i++)assert.ok(ground[i].x-(ground[i-1].x+ground[i-1].w)<=190);for(const it of l.items.filter(i=>i.type==='paw'||i.type==='power'))assert.ok(l.platforms.some(s=>it.x+28>s.x&&it.x<s.x+s.w&&s.y>=it.y&&s.y-it.y<160),`Unsupported ${it.type} at ${it.x}`)});
