import {Game} from './engine.js';
import {Renderer,drawMike,drawCat} from './art.js';
import {Audio} from './audio.js';
import {loadCharacters} from './characters.js';
import {bindTouchControls} from './touch.js';
import {openingMarkup,loadOpeningArt,initializeOpening} from './opening.js';
const $=s=>document.querySelector(s),screen=$('#screen'),canvas=$('#game'),hud=$('#hud');
const audio=new Audio(),renderer=new Renderer(canvas);
const STORAGE='super-mike-oh-v1';
let data={settings:{sound:false,music:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches},best:0,completed:false,save:null};
try{const parsed=JSON.parse(localStorage.getItem(STORAGE));if(parsed&&typeof parsed==='object'){data={...data,...parsed,settings:{...data.settings,...parsed.settings}};if(data.save&&(!Array.isArray(data.save.collected)||!Number.isFinite(data.save.lives)))data.save=null}}catch{}
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(data))}catch{toast('Saving is unavailable in this browser. You can still play.')}}
let openingReady=false;
let toastTimer,winTimer,previousPanel='menu',hudStamp='',gamepadPrevious={},lastAutoSave=0;
const game=new Game((type,message)=>{
  if(type==='toast')toast(message);
  else if(type==='state')updateHUD();
  else if(type==='save'){data.save=game.snapshot();persist()}
  else if(type==='gameover'){data.save=null;persist();showGameOver()}
  else if(type==='win'){audio.sfx('win');data.best=Math.max(data.best,game.score);data.completed=true;data.save=null;persist();winTimer=setTimeout(showVictory,2300)}
  else {audio.sfx(type);if(type==='power')toast('SUPER MIKE MODE · Same Mike. Bigger power.');if(type==='checkpoint')audio.sfx('checkpoint')}
});
// The constructor emits before the game binding is assigned; HUD updates begin after initialization.
function updateHUD(){if(!window.__mikeReady)return;const stamp=[game.lives,game.coins,game.paws,game.score,game.player.super,game.level.cave].join();if(stamp===hudStamp)return;hudStamp=stamp;$('#hud-lives').textContent='♥ '.repeat(Math.max(0,Math.min(5,game.lives)))+(game.lives>5?`+${game.lives-5}`:'');$('#hud-coins').textContent=String(game.coins).padStart(2,'0');$('#hud-paws').textContent=`${game.paws}/3`;$('#hud-score').textContent=String(game.score).padStart(6,'0');$('#hud-power').textContent=game.player.super?'✦ SUPER MIKE':'NORMAL MIKE';$('#hud-zone').textContent=game.level.cave?'THE WHISKER CAVERN':'GREEN PAW MEADOWS'}
window.__mikeReady=true;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function settingsApply(){audio.enabled=!!data.settings.sound;audio.music=!!data.settings.music;renderer.reduced=!!data.settings.reduced;$('#sound-button').classList.toggle('sound-on',audio.enabled);$('#sound-button').setAttribute('aria-label',audio.enabled?'Mute sound':'Enable sound');$('#sound-button').setAttribute('aria-pressed',String(audio.enabled))}
settingsApply();
function catPortrait(){const c=$('.story-cat');if(c)drawCat(c.getContext('2d'),75,110,1.4,'prince',game.time,true)}
function modal(content){$('#touch-controls').hidden=true;screen.innerHTML=`<div class="modal-shade"><section class="modal" role="dialog" aria-modal="true">${content}</section></div>`;catPortrait();requestAnimationFrame(()=>screen.querySelector('button')?.focus())}
function startPlay(saved=false){$('#game-shell').classList.add('is-session');lastAutoSave=0;clearTimeout(winTimer);game.reset(saved?data.save:null);game.mode='playing';screen.innerHTML='';hud.hidden=false;$('#game-bottom').hidden=true;$('#touch-controls').hidden=false;clearInput();canvas.focus({preventScroll:true});audio.unlock();updateHUD();toast(saved?'Welcome back, Mike. Your checkpoint is ready.':'GREEN PAW MEADOWS · Prince Xiaboo needs you!');data.save=game.snapshot();persist()}
function showMenu(){$('#game-shell').classList.remove('is-opening');$('#game-shell').classList.remove('is-session');clearTimeout(winTimer);if(game.mode==='playing'||game.mode==='paused'){data.save=game.snapshot();persist()}game.mode='menu';game.level=game.main;hud.hidden=true;$('#touch-controls').hidden=true;$('#game-bottom').hidden=false;clearInput();screen.innerHTML=`<div class="title-screen"><div class="title-copy"><span class="eyebrow">WELCOME TO THE KINGDOM OF XIABOO</span><h1>SUPER<span>MIKE-OH!</span></h1><p>One ordinary guy. One extraordinary cat.<br>A whole kingdom between them.</p><div class="title-actions"><button class="primary-button" data-action="start">Let’s adventure <span>→</span></button>${data.save?'<button class="continue-button" data-action="continue">Continue ↗</button>':'<button class="continue-button" data-action="how">How to play ↗</button>'}</div><div class="title-note">START SMALL. &nbsp; POWER UP. &nbsp; SAVE THE PRINCE.</div><div class="menu-utilities"><button data-action="levels">Level select</button><span>·</span><button data-action="settings">Settings</button><span>·</span><button data-action="credits">Credits</button></div></div><div class="world-tag"><span>✧</span><div><small>YOUR FIRST CHAPTER</small><b>Green Paw Meadows</b></div></div><div class="character-tag"><strong>Prince Xiaboo</strong> · worth every jump.</div></div>`}
function intro(){game.mode='intro';hud.hidden=true;$('#game-bottom').hidden=true;modal(`<span class="eyebrow">THE ADVENTURE BEGINS</span><canvas class="story-cat" width="150" height="125" aria-label="Prince Xiaboo, a cream royal cat"></canvas><h2>A tiny crown.<br>A very big problem.</h2><p>A mysterious army of mischievous cats has swept through the kingdom. Prince Xiaboo has been taken to the royal lookout beyond the meadows.</p><p><strong>Mike! Your favorite little royal needs you.</strong></p><div class="modal-actions"><button class="primary-button" data-action="play">I’m coming, Xiaboo! <span>→</span></button></div><button class="text-button" data-action="home">Back to the kingdom</button>`)}
function pause(){if(game.mode!=='playing')return;game.mode='paused';clearInput();data.save=game.snapshot();persist();modal(`<span class="eyebrow">TAKE A LITTLE BREATHER</span><h2>Adventure on pause.</h2><p>The cats can wait. Your checkpoint is saved on this device.</p><div class="modal-actions"><button class="primary-button" data-action="resume">Keep adventuring →</button><button class="secondary-button" data-action="checkpoint">Restart checkpoint</button></div><button class="text-button" data-action="settings">Settings</button><button class="text-button" data-action="home">Main menu</button>`)}
function resume(){game.mode='playing';screen.innerHTML='';$('#touch-controls').hidden=false;clearInput();canvas.focus({preventScroll:true})}
function back(){previousPanel==='paused'?pauseFromPanel():showMenu()}
function pauseFromPanel(){game.mode='playing';pause()}
function how(){previousPanel=game.mode==='playing'||game.mode==='paused'?'paused':'menu';if(previousPanel==='paused')game.mode='paused';clearInput();modal(`<span class="eyebrow">A LITTLE FIELD GUIDE</span><h2>You’ve got this, Mike.</h2><div class="controls-list"><div><kbd>← →</kbd> / A D · Move</div><div><kbd>SPACE</kbd> Hold for a high jump</div><div><kbd>SHIFT</kbd> Sprint</div><div><kbd>↓</kbd> / S · Duck / enter pipe</div><div><kbd>X</kbd> Super power punch</div><div><kbd>ESC</kbd> Pause</div></div><p>Jump onto cats to bounce away. Armored cats need two stomps, or one Super Mike hit. Follow the coins, look for the glowing M Capsule, and press down on pipes marked with an arrow.</p><p>On mobile, tap RUN to toggle sprint, then hold a direction and tap or hold Jump. Rotate your phone for a wider view. Controller: stick / D-pad to move, A to jump, B to sprint, X to punch, Start to pause. Three royal paw tokens are hidden in the level.</p><div class="modal-actions"><button class="primary-button" data-action="back">Got it. Let’s go →</button><button class="secondary-button" data-action="levels">Level select</button></div>`)}
function settings(){previousPanel=game.mode==='playing'||game.mode==='paused'?'paused':'menu';if(previousPanel==='paused')game.mode='paused';modal(`<span class="eyebrow">MAKE YOURSELF AT HOME</span><h2>Your kind of adventure.</h2><label class="settings-row">Sound effects<input type="checkbox" data-setting="sound" ${data.settings.sound?'checked':''}></label><label class="settings-row">Original adventure music<input type="checkbox" data-setting="music" ${data.settings.music?'checked':''}></label><label class="settings-row">Reduce background motion<input type="checkbox" data-setting="reduced" ${data.settings.reduced?'checked':''}></label><p>Progress and preferences are saved in this browser on this device.</p><div class="modal-actions"><button class="primary-button" data-action="back">All set →</button></div>`)}
function credits(){previousPanel=game.mode==='playing'||game.mode==='paused'?'paused':'menu';if(previousPanel==='paused')game.mode='paused';modal(`<span class="eyebrow">SMALL CAT. BIG KINGDOM. BIGGER HEART.</span><canvas class="story-cat" width="150" height="125"></canvas><h2>For the royal cat<br>worth saving.</h2><p>SUPER MIKE-OH is an original adventure about everyday courage, a surprisingly powerful protein capsule, and one very loved cat.</p><p>Mike and Prince Xiaboo are inspired by your character references. All in-game illustrations, environments, melodies, and sounds were made for this game.</p><p><strong>Chapter one: Green Paw Meadows</strong><br>One complete level, a hidden cavern, and a royal reunion.</p><div class="modal-actions"><button class="primary-button" data-action="back">Back to the adventure →</button><button class="secondary-button" data-action="settings">Settings</button></div>`)}
function levels(){modal(`<span class="eyebrow">CHOOSE YOUR ADVENTURE</span><h2>The Kingdom of Xiaboo</h2><button class="level-choice" data-action="start"><span><strong>01 · Green Paw Meadows</strong><small>${data.completed?'Completed · Replay for all three paws':'Meadows · Secret cavern · Royal lookout'}</small></span><span>→</span></button><p>Personal best: <strong>${data.best.toLocaleString()}</strong><br>This edition contains one complete, replayable chapter.</p><button class="secondary-button" data-action="back">Back</button>`)}
function showGameOver(){clearInput();modal(`<span class="eyebrow">EVERY HERO NEEDS ANOTHER TRY</span><h2>Not yet, Mike!</h2><canvas class="story-cat" width="150" height="125"></canvas><p>Prince Xiaboo still needs you.<br>Shake out those legs. There’s more adventure in you.</p><div class="modal-actions"><button class="primary-button" data-action="play">Try again →</button><button class="secondary-button" data-action="home">Main menu</button></div>`)}
function showVictory(){if(game.mode!=='won')return;modal(`<span class="eyebrow">MIKE-OH! · LEVEL COMPLETE</span><canvas class="story-cat" width="150" height="125"></canvas><h2>Prince Xiaboo saved!</h2><p>The tiniest crown is back where it belongs.<br>The kingdom is safe. Thank you, Mike!</p><div class="results"><div><b>${game.coins}</b><small>MIKE COINS</small></div><div><b>${game.paws}/3</b><small>ROYAL PAWS</small></div><div><b>${game.kills}</b><small>CATS DEFEATED</small></div><div><b>${Math.floor(game.elapsed/60)}:${String(Math.floor(game.elapsed%60)).padStart(2,'0')}</b><small>YOUR TIME</small></div><div><b>${game.score.toLocaleString()}</b><small>TOTAL SCORE</small></div><div><b>+${game.bonus}</b><small>FINISH BONUS</small></div></div><div class="modal-actions"><button class="primary-button" data-action="play">One more adventure →</button><button class="secondary-button" data-action="home">Main menu</button></div>`)}
const actions={enter:()=>{if(openingReady)showMenu()},home:()=>{if(openingReady)showMenu()},start:intro,play:()=>startPlay(),continue:()=>startPlay(true),how,credits,settings,levels,back,resume,checkpoint:()=>{game.respawn();resume();toast('A fresh start at your checkpoint.')},fullscreen:async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#game-shell').requestFullscreen()}catch{toast('Fullscreen is unavailable here. Try rotating your device.')}}};
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){if(!openingReady&&a.dataset.action!=='fullscreen')return;audio.unlock();actions[a.dataset.action]?.()}});
document.addEventListener('change',e=>{if(e.target.dataset.setting){data.settings[e.target.dataset.setting]=e.target.checked;audio.unlock();settingsApply();persist()}});
$('#sound-button').addEventListener('click',()=>{data.settings.sound=!data.settings.sound;audio.unlock();settingsApply();persist();if(audio.enabled)audio.sfx('coin')});
$('#pause-button').addEventListener('click',pause);
const keys={},touchKeys={},keyMap={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'jump',ArrowUp:'jump',KeyW:'jump',ShiftLeft:'run',ShiftRight:'run',ArrowDown:'down',KeyS:'down',KeyX:'attack'};
let jumpPressed=false,attackPressed=false,touchInput;
function clearInput(){for(const k in keys)delete keys[k];for(const k in touchKeys)delete touchKeys[k];touchInput?.clear();jumpPressed=false;attackPressed=false}
document.addEventListener('keydown',e=>{
  if(e.code==='Escape'){if(game.mode==='playing'){e.preventDefault();pause()}else if(game.mode==='paused'){e.preventDefault();resume()}return}
  if(e.code==='Tab'&&screen.querySelector('[role="dialog"]')){const f=[...screen.querySelectorAll('button,input')],i=f.indexOf(document.activeElement);if(e.shiftKey&&i<=0){e.preventDefault();f.at(-1)?.focus()}else if(!e.shiftKey&&i===f.length-1){e.preventDefault();f[0]?.focus()}return}
  if(game.mode!=='playing')return;const key=keyMap[e.code];if(!key)return;e.preventDefault();if(!keys[key]&&!e.repeat){if(key==='jump')jumpPressed=true;if(key==='attack')attackPressed=true}keys[key]=true;
});
document.addEventListener('keyup',e=>{const key=keyMap[e.code];if(key){keys[key]=false;if(game.mode==='playing')e.preventDefault()}});
touchInput=bindTouchControls([...document.querySelectorAll('[data-key]')],touchKeys,{
  enabled:()=>game.mode==='playing',unlock:()=>audio.unlock(),
  onPress:key=>{if(key==='jump')jumpPressed=true;if(key==='attack')attackPressed=true},
});
window.addEventListener('blur',()=>{clearInput();if(game.mode==='playing')pause()});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.mode==='playing')pause()});
window.addEventListener('pagehide',()=>{if(['playing','paused'].includes(game.mode)){data.save=game.snapshot();persist()}});
function gamepad(){const pad=navigator.getGamepads?.()?.find(p=>p?.connected);if(!pad){gamepadPrevious={};return {}}const b=i=>pad.buttons[i]?.pressed;const state={left:pad.axes[0]<-.25||b(14),right:pad.axes[0]>.25||b(15),down:pad.axes[1]>.5||b(13),jump:b(0),run:b(1)||b(5),attack:b(2),pause:b(9)};if(state.jump&&!gamepadPrevious.jump)jumpPressed=true;if(state.attack&&!gamepadPrevious.attack)attackPressed=true;if(state.pause&&!gamepadPrevious.pause){if(game.mode==='playing')pause();else if(game.mode==='paused')resume()}gamepadPrevious=state;return state}
new ResizeObserver(()=>{renderer.resize();game.viewWidth=renderer.w}).observe(canvas);
renderer.resize();game.viewWidth=renderer.w;
let last=performance.now();
function frame(now){const dt=Math.min((now-last)/1000,.035);last=now;const pad=gamepad();const input={};for(const key of ['left','right','jump','down','run','attack'])input[key]=keys[key]||touchKeys[key]||pad[key];input.jumpPressed=jumpPressed;input.attackPressed=attackPressed;game.step(dt,input);jumpPressed=false;attackPressed=false;renderer.render(game);audio.step(dt,game.level.cave,game.mode==='playing');if(game.mode==='playing'&&game.elapsed-lastAutoSave>12){lastAutoSave=game.elapsed;data.save=game.snapshot();persist()}requestAnimationFrame(frame)}
game.mode='loading';$('#game-shell').classList.add('is-opening');$('#game-bottom').hidden=true;
screen.innerHTML=openingMarkup();requestAnimationFrame(frame);
const failures=await initializeOpening([
  {name:'characters',message:'Mike is ready for adventure.',run:()=>loadCharacters()},
  {name:'opening-art',message:'The royal company has arrived.',run:()=>loadOpeningArt()},
  {name:'title-font',message:'Putting the finishing touches on the kingdom.',run:()=>document.fonts.load?.('24px "Super Mario 256"')||document.fonts.ready},
],(percent,message)=>{
  $('#loading-fill').style.width=`${percent}%`;$('#loading-percent').textContent=`${percent}%`;
  $('#opening-progress').setAttribute('aria-valuenow',String(percent));$('#loading-message').textContent=message;
});
openingReady=true;$('#loading-message').textContent=failures.length?'Ready to play. Some artwork could not load; refresh to retry.':'READY, MIKE-OH!';
$('#opening-enter').disabled=false;$('#opening-enter').textContent='ENTER THE KINGDOM';
$('#opening-enter').focus({preventScroll:true});
